# Generated by Django 4.1.7 on 2023-03-24 11:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("startup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In Progress", "In Progress"),
                        ],
                        max_length=15,
                    ),
                ),
                ("domain", models.CharField(max_length=100)),
                ("project_cover_picture_url", models.URLField(blank=True)),
                (
                    "incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="startup.team"
                    ),
                ),
            ],
        ),
    ]
