# Generated by Django 4.1.7 on 2023-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startup", "0002_startupproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startupproject",
            name="project_cover_picture_url",
        ),
        migrations.AddField(
            model_name="startupproject",
            name="project_cover_picture",
            field=models.ImageField(blank=True, upload_to="startup_project_pics"),
        ),
        migrations.AlterField(
            model_name="startupproject",
            name="status",
            field=models.CharField(
                choices=[("Completed", "Completed"), ("In Progress", "In Progress")],
                default="In Progress",
                max_length=15,
            ),
        ),
    ]
