# Generated by Django 4.1.7 on 2023-03-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("research", "__first__"),
        ("startup", "0002_startupproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateField()),
                ("slug", models.SlugField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "research_projects",
                    models.ManyToManyField(blank=True, to="research.researchproject"),
                ),
                (
                    "startup_projects",
                    models.ManyToManyField(blank=True, to="startup.startupproject"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
