# Generated by Django 4.1.7 on 2023-03-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_research_projects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="members_profile_pics"),
        ),
    ]
