# Generated by Django 4.1.7 on 2023-03-26 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="OwnState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=1000)),
                ("domain", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(blank=True, max_length=1000)),
                ("description", models.CharField(blank=True, max_length=1000)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Energy Engineering", "Energy Engineering"),
                            (
                                "Electrical and Electronics Engineering",
                                "Electrical and Electronics Engineering",
                            ),
                            (
                                "Textile and Fashion Technology",
                                "Textile and Fashion Technology",
                            ),
                            (
                                "Robotics and Autonomous Systems",
                                "Robotics and Autonomous Systems",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "hardness",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        choices=[
                            ("8754730843", "8754730843"),
                            ("9159670084", " 9159670084"),
                            ("7089042384", "7089042384"),
                            ("9629013870", "9629013870"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        choices=[
                            ("Janarthanan venkatachalam", "Janarthanan venkatachalam"),
                            ("Veeramanikandan C", "Veeramanikandan C"),
                            ("Aditi Nayak", "Aditi Nayak"),
                            ("Sushrut", "Sushrut"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("leader_name", models.CharField(max_length=50)),
                ("leader_email", models.CharField(max_length=50, unique=True)),
                ("leader_contact", models.CharField(max_length=25, unique=True)),
                ("leader_rollno", models.CharField(max_length=25, unique=True)),
                (
                    "hashid",
                    models.CharField(editable=False, max_length=14, unique=True),
                ),
                (
                    "ps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ps.state"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=25, unique=True)),
                ("rollno", models.CharField(max_length=25, unique=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ps.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("leader_name", models.CharField(max_length=50)),
                ("leader_email", models.CharField(max_length=50, unique=True)),
                ("leader_contact", models.CharField(max_length=25, unique=True)),
                ("leader_rollno", models.CharField(max_length=25, unique=True)),
                (
                    "ps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ps.ownstate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=25, unique=True)),
                ("rollno", models.CharField(max_length=25, unique=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ps.ownteam"
                    ),
                ),
            ],
        ),
    ]
