# Generated by Django 4.1.7 on 2023-03-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(blank=True, max_length=1000)),
                ("description", models.CharField(blank=True, max_length=1000)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Energy Engineering", "Energy Engineering"),
                            (
                                "Electrical and Electronics Engineering",
                                "Electrical and Electronics Engineering",
                            ),
                            (
                                "Textile and Fashion Technology",
                                "Textile and Fashion Technology",
                            ),
                            (
                                "Robotics and Autonomous Systems",
                                "Robotics and Autonomous Systems",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "hardness",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        choices=[
                            ("8754730843", "8754730843"),
                            ("9159670084", " 9159670084"),
                            ("7089042384", "7089042384"),
                            ("9629013870", "9629013870"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        choices=[
                            ("Janarthanan venkatachalam", "Janarthanan venkatachalam"),
                            ("Veeramanikandan C", "Veeramanikandan C"),
                            ("Aditi Nayak", "Aditi Nayak"),
                            ("Sushrut", "Sushrut"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
