# Generated by Django 4.1.7 on 2023-03-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="hashid",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
