# Generated by Django 4.1.7 on 2023-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ps", "0002_alter_team_hashid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownteam",
            name="hashid",
            field=models.CharField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
