# Generated by Django 4.1.7 on 2023-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ps", "0003_ownteam_hashid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="contact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("8754730843", "8754730843"),
                    ("9159670084", " 9159670084"),
                    ("7089042384", "7089042384"),
                    ("9629013870", "9629013870"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="contact_person",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janarthanan venkatachalam", "Janarthanan venkatachalam"),
                    ("Veeramanikandan C", "Veeramanikandan C"),
                    ("Aditi Nayak", "Aditi Nayak"),
                    ("Sushrut", "Sushrut"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Energy Engineering", "Energy Engineering"),
                    (
                        "Electrical and Electronics Engineering",
                        "Electrical and Electronics Engineering",
                    ),
                    (
                        "Textile and Fashion Technology",
                        "Textile and Fashion Technology",
                    ),
                    (
                        "Robotics and Autonomous Systems",
                        "Robotics and Autonomous Systems",
                    ),
                    ("Sustainable Technology", "Sustainable Technology"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="hardness",
            field=models.CharField(
                blank=True,
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                max_length=25,
                null=True,
            ),
        ),
    ]
