# Generated by Django 4.1.7 on 2023-03-25 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ps", "0003_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=25, unique=True)),
                ("rollno", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
        migrations.AddField(
            model_name="team",
            name="leader_contact",
            field=models.CharField(default=0, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="leader_email",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="leader_name",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="leader_rollno",
            field=models.CharField(default=0, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="team_name",
            field=models.CharField(
                default=0,
                max_length=50,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participants",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ps.team"
            ),
        ),
    ]
