# Generated by Django 4.1.7 on 2023-03-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ps", "0004_participants_delete_member_remove_team_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="ps",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="ps.state"
            ),
            preserve_default=False,
        ),
    ]
