# Generated by Django 4.1.7 on 2023-03-26 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ps", "0005_team_ps"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=1000)),
                ("domain", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OwnTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("leader_name", models.CharField(max_length=50)),
                ("leader_email", models.CharField(max_length=50, unique=True)),
                ("leader_contact", models.CharField(max_length=25, unique=True)),
                ("leader_rollno", models.CharField(max_length=25, unique=True)),
                (
                    "ps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ps.ownstate"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("contact", models.CharField(max_length=25, unique=True)),
                ("rollno", models.CharField(max_length=25, unique=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ps.ownteam"
                    ),
                ),
            ],
        ),
    ]
