# Generated by Django 4.1.7 on 2023-03-24 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="researchproject",
            old_name="project_cover_picture_url",
            new_name="project_cover_picture",
        ),
    ]
