# Generated by Django 4.1.7 on 2023-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "research",
            "0002_rename_project_cover_picture_url_researchproject_project_cover_picture",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchproject",
            name="project_cover_picture",
            field=models.ImageField(blank=True, upload_to="research_project_pics"),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="status",
            field=models.CharField(
                choices=[("Completed", "Completed"), ("In Progress", "In Progress")],
                default="In Progress",
                max_length=15,
            ),
        ),
    ]
