# Generated by Django 4.1.7 on 2023-03-26 01:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0003_alter_researchproject_project_cover_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="short_description",
            field=ckeditor.fields.RichTextField(default="", max_length=50),
        ),
    ]
