# Generated by Django 4.1.7 on 2023-03-26 01:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0004_researchproject_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchproject",
            name="short_description",
            field=ckeditor.fields.RichTextField(default="", max_length=200),
        ),
    ]
