# Generated by Django 4.1.7 on 2023-03-26 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("am", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="cover_image",
            new_name="cover_picture",
        ),
    ]
