# Generated by Django 4.1.7 on 2023-03-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("am", "0002_rename_cover_image_event_cover_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="events_posters"),
        ),
    ]
