# Generated by Django 4.1.7 on 2023-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("am", "0003_event_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.TextField(max_length=200),
        ),
    ]
