# Generated by Django 4.1.7 on 2023-03-26 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("am", "0004_alter_event_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
