# Generated by Django 4.1.7 on 2023-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("am", "0005_alter_event_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
